src/mcl_3dl.cpp

Add matched/unmatched pointclouds output.

---

src/mcl_3dl.cpp

Fix init_yaw/pitch/roll setting.

---

README.md
doc/Algorithms.md

adds README.md

---

launch/mcl_3dl.rviz
launch/test.launch

* This fixes #3.
* A dataset for testing will be supplied in future.

Add sample launch file.

---

src/mcl_3dl.cpp

Fix beam_model raycast origin.

---

src/quat.hpp

fixes axis-angle value range

---

src/mcl_3dl.cpp
src/nd.hpp
src/pf.hpp

adds hysteresis on final estimation

---

CMakeLists.txt
launch/test.launch
package.xml
test/CMakeLists.txt
test/src/compare_pose.cpp
test/tests/localization_rostest.test.in

adds localization accuracy test

---

src/mcl_3dl.cpp
test/tests/localization_rostest.test.in

rejects total reflection points in beam_model

---

launch/test.launch
src/mcl_3dl.cpp

fixes published tf timestamps to have a future date

---

launch/test.launch

* related to #56 
* waiting for at-wat/neonavigation#30

adds example without odometry

---

include/filter.h
include/pf.h
src/mcl_3dl.cpp

* fix number of selected points for likelihood calculation
* add error recovering / asserts

Fix a bug where all particle probabilities get zero.

---

.dockerignore
.travis.scripts/install_deps.sh
.travis.scripts/save_cache.sh
.travis.scripts/test.sh
.travis.yml
CMakeLists.txt
Dockerfile.indigo
test/CMakeLists.txt

Fix build on indigo.

---

src/mcl_3dl.cpp

- wrong:
`nd(mean = 1.0, sigma = sigma_trans_trans) * nd(mean = 1.0, sigma = sigma_rot_trans)`
- corrected:
`nd(mean = 0.0, sigma = sigma_trans_trans) + nd(mean = 0.0, sigma = sigma_rot_trans)`

Fix odometry noise function.

---

test/src/test_pf.cpp

Add test for pf::ParticleFilter.

---

include/pf.h

Fix particle resize

---

include/pf.h
src/mcl_3dl.cpp

Add global localization

---

include/raycast.h
src/mcl_3dl.cpp

Hit was checked by using range search with (grid/2.0) which make a
lot of miss detection. (sqrt(2.0) * grid / 2.0) should be good
approximation.

Fix raycast

---

src/mcl_3dl.cpp

angular version of #99 
fixes #106

Add integral angular odometry error constraint

---

include/raycast.h
src/mcl_3dl.cpp
test/CMakeLists.txt
test/src/test_raycast.cpp

Add unit tests for Raycast

---

CMakeLists.txt
msg/Status.msg
src/mcl_3dl.cpp

also fix NodeHandle usage
---
fixes #118

Add localization status output

---

include/compatibility.h
launch/test.launch
src/mcl_3dl.cpp
test/tests/localization_rostest.test.in
test/tests/tf_rostest.test.in

compatible mode as default at now

Migrate to ROS recommended namespace model

---

test/CMakeLists.txt

Remove CMake warning message

---

Dockerfile.indigo
Dockerfile.kinetic

Test with shadow-fixed repository

---

CMakeLists.txt

Compile with PCL_NO_PRECOMPILE

---

src/mcl_3dl.cpp
test/CMakeLists.txt
test/src/test_transform_failure.cpp
test/tests/transform_rostest.test

Add tf exception handling and change message level

---

README.md
doc/Parameters.md
src/mcl_3dl.cpp

Refactor likelihood calculation

---

test/CMakeLists.txt
test/src/test_expansion_resetting.cpp
test/tests/expansion_resetting_rostest.test

Add test for expansion resetting

---

include/mcl_3dl/parameters.h
include/mcl_3dl/pf.h
include/mcl_3dl/quat.h
include/mcl_3dl/raycast.h
include/mcl_3dl/state_6dof.h
include/mcl_3dl/vec3.h
src/lidar_measurement_model_beam.cpp
src/mcl_3dl.cpp
test/src/test_quat.cpp
test/src/test_vec3.cpp

Fix class member naming style

---

CMakeLists.txt
package.xml
src/mcl_3dl.cpp
test/src/compare_tf.cpp
test/src/test_expansion_resetting.cpp
test/src/test_global_localization.cpp
test/src/test_transform_failure.cpp
test/tests/expansion_resetting_rostest.test
test/tests/global_localization_rostest.test

Migrate tf to tf2

---

src/mcl_3dl.cpp

ref https://github.com/at-wat/mcl_3dl/pull/208#discussion_r238147673
---
fix #213

Fix tf timestamp

---

src/mcl_3dl.cpp

https://github.com/at-wat/mcl_3dl/pull/208#discussion_r244629280

Reduce memcpy in point cloud transform

---

.post-release/Dockerfile
.post-release/README.md
.post-release/docker-compose.yml
.post-release/post-release-test.sh
.post-release/test.sh

Add post-release test script

---

include/mcl_3dl/motion_prediction_model_base.h
include/mcl_3dl/motion_prediction_models/motion_prediction_model_differential_drive.h
src/mcl_3dl.cpp
test/CMakeLists.txt
test/src/test_motion_prediction_model_differential_drive.cpp

Refactor motion prediction models

---

include/mcl_3dl/pf.h
test/src/test_pf.cpp

Closes #232 
* Fix resample() to remove first particle correctly.
* A test is added to verify this fix.

Fix ParticleFilter::resample()

---

src/mcl_3dl.cpp
test/src/test_global_localization.cpp
test/tests/global_localization_rostest.test

Clear odometry integration error on global localization

---

.travis.yml
.travis/Dockerfile
.travis/test.sh

- disable docker layer cache
- use python3

Refactor CI scripts

---

test/src/test_expansion_resetting.cpp
test/src/test_global_localization.cpp

Fix flaky rostest nodes

---

src/mcl_3dl.cpp

Add validation for orientation of initial pose

---

test/tests/global_localization_rostest.test

Fix global localization test parameter

---

src/mcl_3dl.cpp

It does not look like the use of `sensor_msgs::PointCloud` is necessary. For consistency, using `sensor_msgs::PointCloud2` seems better.

Remove references to sensor_msgs::PointCloud

---

test/src/test_beam_label.cpp
test/src/test_expansion_resetting.cpp
test/src/test_global_localization.cpp
test/src/test_landmark.cpp

Improve test stability

---

CHANGELOG.rst
package.xml

Release 0.5.2

---

.github/workflows/prerelease.yaml
CHANGELOG.rst
package.xml

Release 0.5.3

---

test/src/test_beam_label.cpp
test/tests/beam_label_rostest.test
test/tests/localization_rostest.test.in

- Publish reference data with latch
- Fix test name
- Fix pointcloud esolution of test_beam_label

Fix flaky tests

---

doc/Parameters.md
src/mcl_3dl.cpp

Add odom/imu/cloud_queue_size params

---

CHANGELOG.rst
package.xml

Release 0.5.4

---

include/mcl_3dl/chunked_kdtree.h
src/mcl_3dl.cpp

`boost::shared_ptr` is replaced by `std::shared_ptr` since 1.11

Support PCL 1.11 and later

---

CHANGELOG.rst
package.xml

Release 0.6.1

---

CHANGELOG.rst
package.xml

Release 0.6.4

---

include/mcl_3dl/chunked_kdtree.h
include/mcl_3dl/filter.h
include/mcl_3dl/nd.h
include/mcl_3dl/pf.h
include/mcl_3dl/quat.h
include/mcl_3dl/raycast.h
include/mcl_3dl/raycasts/raycast_using_dda.h
include/mcl_3dl/raycasts/raycast_using_kdtree.h
include/mcl_3dl/state_6dof.h
include/mcl_3dl/vec3.h
src/mcl_3dl.cpp
test/tests/beam_label_rostest.test
test/tests/expansion_resetting_rostest.test

Just a few minor things I came across when browsing the code base.

Minor changes
